import { computed, ref } from 'vue';

type Locale = 'zh' | 'en';
const saved = localStorage.getItem('mph-locale') as Locale | null;
export const locale = ref<Locale>(saved === 'en' ? 'en' : 'zh');
const messages: Record<Locale, Record<string, string>> = {
  zh: {
    brand:'模型价格中心', brandSub:'官方价格情报', live:'实时目录', workspace:'工作台', admin:'管理后台', catalog:'价格目录',
    index:'价格索引 / 2026', hero:'让每一次模型决策，都清晰可见。', heroCopy:'汇总官方模型价格、缓存条件、服务档位与数据来源。为需要比较之后再做决定的团队而生。',
    providers:'厂商', models:'模型', records:'价格记录', sources:'官方来源', allProviders:'全部厂商', allModalities:'全部模态', allCurrencies:'全部币种', search:'搜索模型标识...', columns:'显示字段', reset:'重置',
    provider:'厂商', model:'模型', modality:'模态', context:'上下文', deploymentVersion:'部署版本', currency:'币种', unit:'单位', tier:'档位', input:'输入 / 1M', output:'输出 / 1M', cacheRead:'缓存读', cacheWrite:'缓存写', source:'来源',
    officialRecords:'条官方价格记录 · 第 {page} / {pages} 页', previous:'上一页', next:'下一页', noMatch:'没有匹配的价格记录',
    private:'私有工作区', control:'控制中心', controlCopy:'管理官方价格采集器、厂商信息，以及用于故障诊断的语言模型。', username:'管理员账号', password:'管理员密码', enter:'进入工作台', returnCatalog:'返回价格目录',
    operations:'运营 / {section}', collectors:'采集器', languageModels:'语言模型', keepCurrent:'保持价格索引最新。', intelligence:'智能配置层。', runAll:'运行全部采集器', updating:'更新中...', addKey:'新增模型 Key',
    healthy:'正常', review:'待复核', error:'异常', running:'运行中', unavailable:'未启用', never:'未运行', collector:'采集器', status:'状态', providerCollector:'厂商 / 采集器', method:'采集方式', lastRun:'最近运行', indexed:'已入库', actions:'操作', officialMonitors:'官方来源监控', refresh:'刷新状态', run:'运行', details:'详情', aiRepair:'AI脚本修复', aiRepairHint:'修复该脚本源码并生成可应用的修复建议', aiRepairOnlyError:'仅确认执行异常后可修复', repairing:'修复中...', repairQueued:'已排队，等待 AI 修复', repairSuggested:'已生成修复建议', repairFailed:'修复失败', browserRequired:'必须 Playwright', httpThenBrowser:'HTTP 优先 / 浏览器兜底', httpOnly:'纯 HTTP', browserOcr:'浏览器 + 视觉 OCR', browserOff:'Playwright 未启用', browserOn:'Playwright 已启用', emptyResult:'空结果', successResult:'采集成功', skippedResult:'已跳过', failedResult:'执行失败', sourceCode:'源码', editSource:'编辑采集器源码', saveSource:'保存源码', repairSource:'AI 修复源码', addScraper:'新增采集器', officialCoverage:'官方覆盖面', providerName:'厂商名称', scraperName:'采集器标识', pricingUrl:'定价网址', requirements:'采集需求', generate:'AI 编写脚本', generated:'已生成草稿', coverageNote:'LiteLLM 仅用于覆盖面旁证，官方身份必须以厂商自有官网为准。',
    configuredModels:'已配置的语言模型', noKeys:'尚未配置模型 Key。', enabled:'已启用', disabled:'已停用', test:'测试', edit:'编辑', delete:'删除', collectorDetail:'采集器详情', modelConfig:'语言模型配置', editKey:'编辑模型 Key', addModelKey:'新增模型 Key', name:'名称', baseUrl:'Base URL', apiKey:'API Key', modelField:'模型', cancel:'取消', save:'保存', close:'关闭', signOut:'退出登录', viewCatalog:'查看目录', connectionOk:'连接正常', connectionFailed:'连接失败', deleteConfirm:'确认删除这个 Key 吗？',
  },
  en: {
    brand:'Model Price Hub', brandSub:'Official pricing intelligence', live:'Live catalog', workspace:'Workspace', admin:'Admin', catalog:'Pricing catalog',
    index:'The pricing index / 2026', hero:'Clarity for every model decision.', heroCopy:'A considered index of official model pricing, cache conditions, service tiers and provider sources. Built for teams who compare before they commit.',
    providers:'Providers', models:'Models', records:'Price records', sources:'Official sources', allProviders:'All providers', allModalities:'All modalities', allCurrencies:'All currencies', search:'Search model identifiers...', columns:'Columns', reset:'Reset',
    provider:'Provider', model:'Model', modality:'Modality', context:'Context', deploymentVersion:'Deployment version', currency:'Currency', unit:'Unit', tier:'Tier', input:'Input / 1M', output:'Output / 1M', cacheRead:'Cache read', cacheWrite:'Cache write', source:'Source',
    officialRecords:'official price records · Page {page} / {pages}', previous:'Previous', next:'Next', noMatch:'No matching prices',
    private:'Private workspace', control:'Control room', controlCopy:'Manage official pricing collectors, provider metadata and the language models used for repair diagnostics.', username:'Username', password:'Password', enter:'Enter workspace', returnCatalog:'Return to catalog',
    operations:'Operations / {section}', collectors:'Collectors', languageModels:'Language models', keepCurrent:'Keep the index current.', intelligence:'The intelligence layer.', runAll:'Run all collectors', updating:'Updating...', addKey:'Add model key',
    healthy:'Healthy', review:'Review', error:'Error', running:'Running', unavailable:'Unavailable', never:'Not run', collector:'Collector', status:'Status', providerCollector:'Provider / collector', method:'Collection method', lastRun:'Last run', indexed:'Indexed', actions:'Actions', officialMonitors:'Official source monitors', refresh:'Refresh status', run:'Run', details:'Details', aiRepair:'AI script repair', aiRepairHint:'Repair this scraper source and generate an applicable fix', aiRepairOnlyError:'Only confirmed execution errors can be repaired', repairing:'Repairing...', repairQueued:'Queued for AI repair', repairSuggested:'Repair suggestion generated', repairFailed:'Repair failed', browserRequired:'Playwright required', httpThenBrowser:'HTTP first / browser fallback', httpOnly:'HTTP only', browserOcr:'Browser + visual OCR', browserOff:'Playwright off', browserOn:'Playwright on', emptyResult:'Empty result', successResult:'Collected', skippedResult:'Skipped', failedResult:'Failed', sourceCode:'Source', editSource:'Edit scraper source', saveSource:'Save source', repairSource:'AI repair source', addScraper:'Add scraper', officialCoverage:'Official coverage', providerName:'Provider name', scraperName:'Scraper id', pricingUrl:'Pricing URL', requirements:'Collection requirements', generate:'Generate with AI', generated:'Draft generated', coverageNote:'LiteLLM is coverage evidence only; official identity must be verified against the vendor website.',
    configuredModels:'Configured language models', noKeys:'No model keys configured.', enabled:'Enabled', disabled:'Disabled', test:'Test', edit:'Edit', delete:'Delete', collectorDetail:'Collector detail', modelConfig:'Language model configuration', editKey:'Edit model key', addModelKey:'Add model key', name:'Name', baseUrl:'Base URL', apiKey:'API key', modelField:'Model', cancel:'Cancel', save:'Save', close:'Close', signOut:'Sign out', viewCatalog:'View catalog', connectionOk:'Connection OK', connectionFailed:'Connection failed', deleteConfirm:'Delete this key?',
  },
};
export function t(key:string, vars:Record<string,string|number>={}):string { return (messages[locale.value][key] || messages.en[key] || key).replace(/\{(\w+)\}/g, (_, name:string) => String(vars[name] ?? `{${name}}`)); }
export function toggleLocale():void { locale.value = locale.value === 'zh' ? 'en' : 'zh'; localStorage.setItem('mph-locale', locale.value); }
export const localeLabel = computed(() => locale.value === 'zh' ? 'EN' : '中文');
