<template>
  <div v-if="!loggedIn" class="login"><form class="login-card" @submit.prevent="login"><div class="eyebrow">{{ t('private') }}</div><h1>{{ t('control') }}</h1><p>{{ t('controlCopy') }}</p><input v-model="credentials.username" class="control" :placeholder="t('username')" required><input v-model="credentials.password" class="control" type="password" :placeholder="t('password')" required><button class="btn primary" type="submit">{{ t('enter') }}</button><small v-if="error" style="color:var(--red);display:block;margin-top:12px">{{ error }}</small><button class="btn ghost" style="display:block;text-align:center;margin-top:12px" type="button" @click="toggleLocale">{{ localeLabel }}</button><RouterLink to="/" class="btn ghost" style="display:block;text-align:center;margin-top:8px">{{ t('returnCatalog') }}</RouterLink></form></div>
  <div v-else class="admin-shell"><aside class="side"><div class="brand"><div class="brand-mark">M</div><div><div class="brand-name">{{ t('brand') }}</div><div class="brand-sub">{{ t('brandSub') }}</div></div></div><div class="nav-label">{{ t('workspace') }}</div><button class="nav-item" :class="{active:pane==='scrapers'}" @click="pane='scrapers'">◌ <span>{{ t('collectors') }}</span></button><button class="nav-item" :class="{active:pane==='keys'}" @click="pane='keys'">⌘ <span>{{ t('languageModels') }}</span></button><div class="side-foot"><RouterLink to="/" class="btn" style="display:block;text-align:center">{{ t('viewCatalog') }}</RouterLink><button class="btn ghost" style="width:100%;margin-top:8px" @click="toggleLocale">{{ localeLabel }}</button><button class="btn ghost" style="width:100%;margin-top:8px" @click="logout">{{ t('signOut') }}</button></div></aside>
    <main class="admin-main"><section class="admin-header"><div><div class="eyebrow">{{ t('operations',{section:pane==='scrapers'?t('collectors'):t('languageModels')}) }}</div><h1 class="admin-title">{{ pane==='scrapers'?t('keepCurrent'):t('intelligence') }}</h1></div><div class="actions"><button v-if="pane==='scrapers'" class="btn" @click="openCoverage">{{ t('officialCoverage') }}</button><button v-if="pane==='scrapers'" class="btn" @click="openNewScraper">{{ t('addScraper') }}</button><button v-if="pane==='scrapers'" class="btn primary" :disabled="runningAll" @click="runAll">{{ runningAll?t('updating'):t('runAll') }}</button><button v-else class="btn primary" @click="openKey()">{{ t('addKey') }}</button></div></section>
      <template v-if="pane==='scrapers'"><section class="dashboard-grid"><div class="dash-card"><span>{{ t('collectors') }}</span><strong>{{ scrapers.length }}</strong></div><div class="dash-card"><span>{{ t('healthy') }}</span><strong style="color:var(--green)">{{ healthy }}</strong></div><div class="dash-card"><span>{{ t('review') }}</span><strong style="color:var(--orange)">{{ errors }}</strong></div><div class="dash-card"><span>{{ t('indexed') }}</span><strong>{{ indexed.toLocaleString() }}</strong></div></section><section class="panel"><div class="panel-head"><div class="panel-title">{{ t('officialMonitors') }}</div><button class="btn ghost" @click="loadScrapers">{{ t('refresh') }}</button></div><div style="overflow:auto"><table class="admin-table"><thead><tr><th>{{ t('status') }}</th><th>{{ t('providerCollector') }}</th><th>{{ t('method') }}</th><th>{{ t('source') }}</th><th>{{ t('lastRun') }}</th><th>{{ t('indexed') }}</th><th>{{ t('actions') }}</th></tr></thead><tbody><tr v-for="item in scrapers" :key="item.name"><td><span class="status"><i class="dot" :class="item.status"></i>{{ statusText[item.status]||item.status }}</span></td><td><span class="vendor">{{ item.vendor_zh||item.provider }}</span><small style="display:block;color:var(--dim);font-family:var(--mono);margin-top:4px">{{ item.name }}</small></td><td><span class="method-tag" :class="item.collection_mode">{{ modeText(item.collection_mode) }}</span><small class="method-note">{{ item.needs_playwright ? (playwrightEnabled ? t('browserOn') : t('browserOff')) : t('httpOnly') }}</small></td><td><a :href="item.source_url" target="_blank">{{ item.domain||item.source_url }} ↗</a></td><td>{{ time(item.last_run) }}</td><td class="number">{{ item.data_rows||0 }}</td><td><div class="actions"><button class="btn" :disabled="item.status==='running'" @click="runOne(item.name)">{{ t('run') }}</button><button class="btn" @click="detail(item.name)">{{ t('details') }}</button><button class="btn" @click="openSource(item.name)">{{ t('sourceCode') }}</button><button class="btn danger" :disabled="repairing===item.name || !['error','warning'].includes(item.status)" :title="['error','warning'].includes(item.status) ? t('aiRepairHint') : t('aiRepairOnlyError')" @click="repair(item.name)">{{ repairing===item.name ? t('repairing') : t('aiRepair') }}</button></div><small v-if="repairMessages[item.name]" class="repair-result" :class="{failed: repairMessages[item.name].failed}">{{ repairMessages[item.name].text }}</small></td></tr></tbody></table></div></section></template>
      <template v-else><section class="panel"><div class="panel-head"><div class="panel-title">{{ t('configuredModels') }}</div></div><div v-if="!keys.length" class="empty">{{ t('noKeys') }}</div><div v-for="key in keys" :key="key.id" class="key-row"><div><strong>{{ key.name }}</strong><span class="tag" style="margin-left:8px">{{ key.protocol==='anthropic'?'Anthropic':'OpenAI' }}</span><span class="tag" style="margin-left:8px">{{ key.enabled?t('enabled'):t('disabled') }}</span><p>{{ key.base_url }} · {{ key.model }}</p><small>{{ (key.purposes||[]).join(' · ') }}</small></div><div class="actions"><button class="btn" @click="testKey(key.id)">{{ t('test') }}</button><button class="btn" @click="openKey(key)">{{ t('edit') }}</button><button class="btn danger" @click="deleteKey(key.id)">{{ t('delete') }}</button></div></div></section></template>
    </main><div v-if="modal" class="modal-layer" @click.self="modal=''" @keydown.esc="modal=''" tabindex="0"><div class="modal wide"><div class="eyebrow">{{ modal==='detail'?t('collectorDetail'):modal==='source'?t('editSource'):modal==='newScraper'?t('addScraper'):modal==='coverage'?t('officialCoverage'):t('modelConfig') }}</div><h2>{{ modal==='detail'?detailData?.name||t('collectorDetail'):modal==='source'?sourceName:modal==='newScraper'?t('addScraper'):modal==='coverage'?t('officialCoverage'):editing?t('editKey'):t('addModelKey') }}</h2><template v-if="modal==='detail'"><pre>{{ JSON.stringify(detailData,null,2) }}</pre><button class="btn" style="margin-top:16px" @click="modal=''">{{ t('close') }}</button></template><template v-else-if="modal==='source'"><textarea v-model="sourceCode" class="code-editor"></textarea><div class="actions" style="justify-content:end;margin-top:14px"><button class="btn" @click="repairSource">{{ t('repairSource') }}</button><button class="btn primary" @click="saveSource">{{ t('saveSource') }}</button></div></template><template v-else-if="modal==='newScraper'"><input v-model="newScraper.provider" class="control" :placeholder="t('providerName')"><input v-model="newScraper.scraper_name" class="control" :placeholder="t('scraperName')"><input v-model="newScraper.source_url" class="control" :placeholder="t('pricingUrl')"><textarea v-model="newScraper.requirements" class="control requirements" :placeholder="t('requirements')"></textarea><div class="actions" style="justify-content:end;margin-top:14px"><button class="btn primary" @click="generateScraper">{{ t('generate') }}</button><button v-if="sourceCode" class="btn" @click="saveGenerated">{{ t('saveSource') }}</button></div><textarea v-if="sourceCode" v-model="sourceCode" class="code-editor"></textarea></template><template v-else-if="modal==='coverage'"><p>{{ t('coverageNote') }}</p><pre>{{ JSON.stringify(coverage,null,2) }}</pre></template><template v-else><input v-model="keyForm.name" class="control" :placeholder="t('name')"><select v-model="keyForm.protocol" class="control"><option value="anthropic">Anthropic Messages</option><option value="openai">OpenAI Compatible</option></select><input v-model="keyForm.base_url" class="control" :placeholder="t('baseUrl')"><input v-model="keyForm.api_key" class="control" :placeholder="t('apiKey')"><input v-model="keyForm.model" class="control" :placeholder="t('modelField')"><input v-model.number="keyForm.max_tokens" class="control" type="number" min="256" max="65536" placeholder="Max tokens"><label class="check"><input v-model="keyForm.enabled" type="checkbox"> {{ t('enabled') }}</label><div class="actions" style="justify-content:end;margin-top:22px"><button class="btn" @click="modal=''">{{ t('cancel') }}</button><button class="btn primary" @click="saveKey">{{ t('save') }}</button></div></template></div></div>
  </div>
</template>
<script setup lang="ts">
import { computed, onMounted, reactive, ref } from 'vue';import { RouterLink } from 'vue-router';import { api } from '../api';import { locale,localeLabel,t,toggleLocale } from '../i18n';
type Scraper={name:string;provider:string;vendor_zh?:string;domain?:string;source_url:string;status:string;collection_mode?:string;needs_playwright?:boolean;last_run?:string;data_rows?:number;items?:number;error?:string;result?:string};type Key={id:string;name:string;protocol:'openai'|'anthropic';base_url:string;api_key:string;model:string;max_tokens?:number;enabled:boolean;purposes:string[]};
const loggedIn=ref(false),error=ref(''),pane=ref<'scrapers'|'keys'>('scrapers'),scrapers=ref<Scraper[]>([]),keys=ref<Key[]>([]),runningAll=ref(false),repairing=ref(''),repairMessages=reactive<Record<string,{text:string;failed?:boolean}>>({}),modal=ref(''),detailData=ref<Record<string,unknown>|null>(null),editing=ref(false),editingId=ref('');const playwrightEnabled=ref(false),sourceName=ref(''),sourceCode=ref(''),coverage=ref<Record<string,unknown>>({}),newScraper=reactive({provider:'',scraper_name:'',source_url:'',requirements:''});const credentials=reactive({username:'',password:''});const keyForm=reactive({name:'',protocol:'openai' as 'openai'|'anthropic',base_url:'https://api.openai.com/v1',api_key:'',model:'gpt-4o-mini',max_tokens:8192,enabled:true});const statusText=computed<Record<string,string>>(()=>({ok:t('healthy'),error:t('error'),warning:t('review'),running:t('running'),unavailable:t('unavailable'),never:t('never')}));const healthy=computed(()=>scrapers.value.filter(s=>s.status==='ok').length),errors=computed(()=>scrapers.value.filter(s=>['error','warning'].includes(s.status)).length),indexed=computed(()=>scrapers.value.reduce((n,s)=>n+(s.data_rows||0),0));
function modeText(mode?:string){return t(mode==='browser_required'?'browserRequired':mode==='http_then_browser'?'httpThenBrowser':mode==='browser_ocr'?'browserOcr':'httpOnly')}async function openSource(name:string){const d=await api<{source_code:string}>(`/admin/scrapers/${encodeURIComponent(name)}/detail`);sourceName.value=name;sourceCode.value=d.source_code;modal.value='source'}async function saveSource(){await api(`/admin/scrapers/${encodeURIComponent(sourceName.value)}/source`,{method:'PUT',body:JSON.stringify({code:sourceCode.value,reason:'admin editor'})});modal.value='';await loadScrapers()}async function repairSource(){
  const d=await api<{task_id:string}>(`/admin/scrapers/${encodeURIComponent(sourceName.value)}/ai-repair`,{method:'POST'});
  const poll=window.setInterval(async()=>{const task=await api<{status:string;progress:number;message:string;repair?:{detail?:{fixed_code?:string}}}>(`/admin/scrapers/${encodeURIComponent(sourceName.value)}/ai-repair/${encodeURIComponent(d.task_id)}`); sourceCode.value=task.repair?.detail?.fixed_code||sourceCode.value; if(task.status==='completed'||task.status==='failed')window.clearInterval(poll)},1000);
}function openNewScraper(){Object.assign(newScraper,{provider:'',scraper_name:'',source_url:'',requirements:''});sourceCode.value='';modal.value='newScraper'}async function generateScraper(){const d=await api<{draft:{code:string}}>('/admin/scrapers/generate',{method:'POST',body:JSON.stringify(newScraper)});sourceCode.value=d.draft.code}async function saveGenerated(){await api(`/admin/scraper-drafts/${encodeURIComponent(newScraper.scraper_name)}/save`,{method:'POST',body:JSON.stringify({code:sourceCode.value})});modal.value='';await loadScrapers()}async function openCoverage(){coverage.value=await api<Record<string,unknown>>('/admin/coverage');modal.value='coverage'}async function login(){try{await api('/admin/login',{method:'POST',body:JSON.stringify(credentials)});loggedIn.value=true;await loadScrapers();await loadKeys()}catch(e){error.value=e instanceof Error?e.message:'Unable to sign in'}}async function logout(){await api('/admin/logout',{method:'POST'}).catch(()=>{});loggedIn.value=false}async function loadScrapers(){const d=await api<{items:Scraper[];runtime?:{playwright:boolean}}>('/admin/scrapers');scrapers.value=d.items;playwrightEnabled.value=Boolean(d.runtime?.playwright)}async function loadKeys(){keys.value=await api<Key[]>('/admin/llm-keys')}async function runOne(name:string){await api(`/admin/scrapers/${encodeURIComponent(name)}/run`,{method:'POST'});await loadScrapers()}async function runAll(){runningAll.value=true;try{await api('/admin/scrapers/run-all',{method:'POST'})}finally{runningAll.value=false;await loadScrapers()}}async function detail(name:string){detailData.value=await api<Record<string,unknown>>(`/admin/scrapers/${encodeURIComponent(name)}/detail`);detailData.value.name=name;modal.value='detail'}async function repair(name:string){
  repairing.value=name; repairMessages[name]={text:t('repairQueued')};
  try{
    const d=await api<{task_id:string}>(`/admin/scrapers/${encodeURIComponent(name)}/ai-repair`,{method:'POST'});
    const poll=window.setInterval(async()=>{
      try{
        const task=await api<{status:string;progress:number;message:string;repair?:{summary?:string};error?:string}>(`/admin/scrapers/${encodeURIComponent(name)}/ai-repair/${encodeURIComponent(d.task_id)}`);
        repairMessages[name]={text:`${task.progress}% · ${task.message}`};
        if(task.status==='completed'||task.status==='failed'){
          window.clearInterval(poll); repairing.value='';
          repairMessages[name]={text:task.status==='completed'?(task.repair?.summary||t('repairSuggested')):(task.error||t('repairFailed')),failed:task.status==='failed'};
          await loadScrapers();
        }
      }catch(e){ window.clearInterval(poll); repairing.value=''; repairMessages[name]={text:e instanceof Error?e.message:t('repairFailed'),failed:true}; }
    },1000);
  }catch(e){ repairing.value=''; repairMessages[name]={text:e instanceof Error?e.message:t('repairFailed'),failed:true}; }
}function openKey(key?:Key){editing.value=!!key;editingId.value=key?.id||'';Object.assign(keyForm,key?{...key,protocol:key.protocol||'openai',api_key:'',max_tokens:key.max_tokens||8192}:{name:'',protocol:'openai',base_url:'https://api.openai.com/v1',api_key:'',model:'gpt-4o-mini',max_tokens:8192,enabled:true});modal.value='key'}async function saveKey(){const body={...keyForm,purposes:['repair']};if(editing.value){await api(`/admin/llm-keys/${editingId.value}`,{method:'PUT',body:JSON.stringify(body)})}else await api('/admin/llm-keys',{method:'POST',body:JSON.stringify(body)});modal.value='';await loadKeys()}async function deleteKey(id:string){if(confirm(t('deleteConfirm'))){await api(`/admin/llm-keys/${id}`,{method:'DELETE'});await loadKeys()}}async function testKey(id:string){const d=await api<{ok:boolean;reply?:string;error?:string}>(`/admin/llm-keys/${id}/test`,{method:'POST'});alert(d.ok?`${t('connectionOk')}: ${d.reply}`:`${t('connectionFailed')}: ${d.error}`)}function time(v?:string){return v?new Date(v).toLocaleString(locale.value==='zh'?'zh-CN':'en-US',{month:'short',day:'numeric',hour:'2-digit',minute:'2-digit'}):'—'}onMounted(async()=>{try{await api('/admin/me');loggedIn.value=true;await loadScrapers();await loadKeys()}catch{loggedIn.value=false}});
</script>
<style scoped>.method-tag{display:inline-block;padding:4px 7px;border:1px solid #bfd0e5;background:#f5f8fc;color:var(--blue);font-size:10px;white-space:nowrap}.method-note{display:block;color:var(--dim);font-size:10px;margin-top:5px}.code-editor{width:100%;min-height:520px;resize:vertical;background:#0d1e36;color:#e8f2ff;border:1px solid #36577e;padding:16px;font:12px/1.6 var(--mono);tab-size:4}.requirements{min-height:120px;resize:vertical}.modal.wide{width:min(980px,100%)}</style>
