<template>
  <div class="shell"><header class="topbar"><div class="brand"><div class="brand-mark">M</div><div><div class="brand-name">{{ t('brand') }}</div><div class="brand-sub">{{ t('brandSub') }}</div></div></div><div class="top-actions"><span class="eyebrow">{{ t('live') }}</span><button class="btn ghost" @click="toggleLocale">{{ localeLabel }}</button><RouterLink class="btn" to="/admin">{{ t('workspace') }}</RouterLink></div></header>
    <main class="page"><section class="hero"><div><div class="eyebrow">{{ t('index') }}</div><h1>{{ t('hero') }}</h1></div><p class="hero-copy">{{ t('heroCopy') }}</p></section>
      <section class="stats"><div v-for="item in stats" :key="item.label" class="stat"><div class="stat-label">{{ item.label }}</div><div class="stat-value">{{ item.value }}</div></div></section>
      <section class="toolbar"><select v-model="filters.vendor" class="control"><option value="">{{ t('allProviders') }}</option><option v-for="v in vendors" :key="v.slug" :value="v.slug">{{ v.zh || v.name }}</option></select><select v-model="filters.modality" class="control"><option value="">{{ t('allModalities') }}</option><option v-for="m in overview?.modalities" :key="m" :value="m">{{ m }}</option></select><select v-model="filters.currency" class="control"><option value="">{{ t('allCurrencies') }}</option><option value="USD">USD</option><option value="CNY">CNY</option></select><input v-model="filters.q" class="control search" :placeholder="t('search')"><div class="field-pop"><button class="btn" @click="fieldOpen=!fieldOpen">{{ t('columns') }} {{ visibleFields.length }}/{{ fields.length }}</button><div v-if="fieldOpen" class="popover"><label v-for="field in fields" :key="field.key"><input v-model="visibleFields" type="checkbox" :value="field.key"> {{ field.label }}</label></div></div><button class="btn ghost" @click="reset">{{ t('reset') }}</button></section>
      <section class="table-frame"><table><colgroup><col v-for="field in activeFields" :key="`col-${field.key}`" :class="`col-${field.key}`"></colgroup><thead><tr><th v-for="field in activeFields" :key="field.key">{{ field.label }}</th></tr></thead><tbody><tr v-for="row in prices.items" :key="`${row.vendor}-${row.model}-${row.cache_state}-${row.service_tier}`"><td v-for="field in activeFields" :key="field.key" :class="field.class"><template v-if="field.key==='vendor'"><span class="vendor">{{ row.vendor_zh || row.vendor_name }}<small>{{ row.vendor }}</small></span></template><template v-else-if="field.key==='model'"><span class="model">{{ row.model }}</span></template><template v-else-if="field.key==='context'">{{ formatContext(row.context_window) }}</template><template v-else-if="field.key==='input'">{{ money(row.input_price) }}</template><template v-else-if="field.key==='output'">{{ money(row.output_price) }}</template><template v-else-if="field.key==='cacheRead'"><span class="cache">{{ money(row.cached_read) }}</span></template><template v-else-if="field.key==='cacheWrite'"><span v-if="row.cached_write" class="cache"><span class="cache-term">{{ cacheTerm(row.cache_state) }}</span>{{ money(row.cached_write) }}</span><span v-else>—</span></template><template v-else-if="field.key==='tier'"><span class="tag">{{ row.service_tier }}</span></template><template v-else-if="field.key==='deployment_version'"><span class="tag">{{ row.deployment_version || '—' }}</span></template><template v-else-if="field.key==='source'"><a :href="row.source_url" target="_blank">{{ row.source }} ↗</a></template><template v-else>{{ (row as Record<string, unknown>)[field.key] || '—' }}</template></td></tr><tr v-if="!prices.items.length"><td :colspan="activeFields.length" class="empty">{{ t('noMatch') }}</td></tr></tbody></table></section>
      <div class="pager"><span>{{ t('officialRecords',{page,pages:pageCount}) }}</span><div class="pager-actions"><button class="btn" :disabled="page===1" @click="goPage(page-1)">{{ t('previous') }}</button><button class="btn" :disabled="page===pageCount" @click="goPage(page+1)">{{ t('next') }}</button></div></div>
    </main></div>
</template>
<script setup lang="ts">
import { computed, onMounted, reactive, ref, watch } from 'vue';import { RouterLink } from 'vue-router';import { getOverview,getPrices,getVendors,type Overview,type PriceResponse,type Vendor } from '../api';import { localeLabel,t,toggleLocale,locale } from '../i18n';
const overview=ref<Overview|null>(null),vendors=ref<Vendor[]>([]),prices=ref<PriceResponse>({total:0,items:[]}),fieldOpen=ref(false),page=ref(1);const pageSize=50;const filters=reactive({vendor:'',modality:'',currency:'',q:''});
const fields=computed(()=>[{key:'vendor',label:t('provider'),class:''},{key:'model',label:t('model'),class:''},{key:'modality',label:t('modality'),class:''},{key:'context',label:t('context'),class:''},{key:'deployment_version',label:t('deploymentVersion'),class:'deployment-version-cell'},{key:'currency',label:t('currency'),class:''},{key:'billing_unit',label:t('unit'),class:''},{key:'tier',label:t('tier'),class:''},{key:'input',label:t('input'),class:'number price-in'},{key:'output',label:t('output'),class:'number price-out'},{key:'cacheRead',label:t('cacheRead'),class:'number cache'},{key:'cacheWrite',label:t('cacheWrite'),class:'number cache'},{key:'source',label:t('source'),class:''}]);const defaultFields=['vendor','model','deployment_version','currency','tier','input','output','cacheRead','cacheWrite','source'];const visibleFields=ref<string[]>(JSON.parse(localStorage.getItem('atelier-fields')||'null')||defaultFields);const activeFields=computed(()=>fields.value.filter(f=>visibleFields.value.includes(f.key)));const pageCount=computed(()=>Math.max(1,Math.ceil(prices.value.total/pageSize)));const stats=computed(()=>[{label:t('providers'),value:overview.value?.vendors||0},{label:t('models'),value:overview.value?.models||0},{label:t('records'),value:overview.value?.prices||0},{label:t('sources'),value:overview.value?.sources.length||0}]);
async function load(){prices.value=await getPrices({vendor:filters.vendor,modality:filters.modality,currency:filters.currency,q:filters.q,limit:pageSize,offset:(page.value-1)*pageSize})}function goPage(next:number){page.value=Math.max(1,Math.min(pageCount.value,next));load()}function reset(){Object.assign(filters,{vendor:'',modality:'',currency:'',q:''});page.value=1}function money(v:number|null){return v===null||v===undefined?'—':v>=1?v.toFixed(2):v.toFixed(4)}function formatContext(v:number|null){return !v?'—':v>=1e6?`${(v/1e6).toFixed(1)}M`:v>=1000?`${(v/1000).toFixed(0)}K`:String(v)}function cacheTerm(v:string|null){return v==='write_5m'?'5 min':v==='write_1h'?'1 hour':'conditional'}watch(filters,()=>{page.value=1;load()},{deep:true});watch(visibleFields,v=>localStorage.setItem('atelier-fields',JSON.stringify(v)),{deep:true});watch(locale,()=>load());onMounted(async()=>{[overview.value,vendors.value]=await Promise.all([getOverview(),getVendors()]);await load()});
</script>
